Initial version of class register
Agata-Gizinska/Class_register pull request #2
Opened 2022-02-21 14:22 UTC by Agata-Gizinska

The aim of this program is to handle data about students, classrooms and courses.
The data are stored in 3 csv-based registers:
- ClassroomRegister - contains classroom name, start and end years, a list of active students, a list of graduates and a list of drop-outs.
- StudentRegister - contains student's data, such as name, date of birth, assigned classroom and assigned courses.
- CourseRegister - cointains course name, a required number of grades for a student to finish the course, a list of active students, a list of graduates of the course and a list of drop-outs of the course.

The program can process data and print them into the console. Moreover, the user should be able to add a new student, add new classroom, add new courses, give grades to students for courses that they attend.
The initial version implement basic classes used by the program: 
- Classroom, Student, Course - used to manipulate data inside the program
- Register (as a parent class) and child classes: ClassroomRegister, StudentRegister, CourseRegister - used to manipulate data which will be stored in csv files.

The program should be accessible to use from command prompt, so the initial version contains argument parser stored in main() function. For now, it is possible to print all registers (print_class, print_students, print_courses) and add a new student to all registers (new_student).

2022-03-03 17:54 UTC, czarnadzuma11 requested changes

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                    pass
```
for row in rows:
  if classroom.name in row:
    row_index = rows.index(row)
    break # break exits the loop early so we stop iteration when row_index is found
````

remove else clause it does not do anything

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                pass
Redundant, just not entering the if clause will have the same effect

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                file.truncate(0)
'r+' does not allow trucating file open with 'rw+'
Also opening with write enabled will truncate file so you can remove this line

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +        new_student_ = Student(*args)
_new_student

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +        with open(self.file, 'r+', newline='', encoding='utf-8') as file:
again, 'rw+' because you are truncating file

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                file.truncate(0)
Remove if you open with 'rw+'

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +        return self.courses
Is there a point to returning self.courses from this function?

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                pass
Again, 
```
else:
  pass
```
is equivalent to not adding else at all, applies to the enire pull request

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +        register.add_student_to_course(student, student.courses[0])
I do not see the point of wrapping  register.add_student_to_course(student, student.courses[0]) with add_student_to_register.
Just do register.add_student_to_course(student, student.courses[0]) and remove this function

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +
one dash parameters are called short and are supposed to be one letter long

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +        first_course = args_[4]
if elif else construction guarantees that only one of actions will be executed but your parser allows to specify multiple of them in one application call.

Either make parser accept only one action at a time https://docs.python.org/3/library/argparse.html#mutual-exclusion
or execute all specified actions (but then you will need to worry about the order in which they were passed)

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +        def is_classroom_in_register(classroom):
this should be a ClassroomRegister method

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                            split(',') if not "''" else []
```if not "''"```
does not compare to anything, you have to do
```if not ("''" == compared_to_value) else []``` or
```if "''" != compared_to_value else []```

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                            if not "''" else []
same

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                            if not "''" else []
same

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                            split(', ') if not "''" else []
same

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +                            if not "''" else []
same

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +        def is_course_in_register(course):
Again, why is this not course method

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +        args_.append(course_reg)
don't do this, just pass them to new_student as named paramterers

2022-03-03 17:54 UTC, czarnadzuma11 commented on class_register.py
> +    parser.add_argument('--new_student', '-newst', nargs=5,
Unacceptable, each of those fields should be a separate named argument.

2022-03-07 06:55 UTC, Agata-Gizinska commented on class_register.py
> +                    pass
ok

2022-03-07 06:55 UTC, Agata-Gizinska commented on class_register.py
> +                pass
ok

2022-03-07 07:34 UTC, Agata-Gizinska commented on class_register.py
> +                file.truncate(0)
File "C:/Users/User/class_register.py", line 39, in add_student_to_classroom
    with open(self.file, 'rw+', newline='', encoding='utf-8') as file:
ValueError: must have exactly one of create/read/write/append mode

Python 3 does not seem to be supporting 'rw+' mode... you can either 'r+' or 'w+', but the problem is that 'w+' truncates whole csv file BEFORE you get data from it - that doesn't do good, because I need to get data from csv first, then process the data that I can append new student info and THEN truncate file and write it with updated data. That is why csv file is opened in 'r+' and truncate is explicitly called.

2022-03-07 07:36 UTC, Agata-Gizinska commented on class_register.py
> +        new_student_ = Student(*args)
why should I make it a private variable? The trailing underscore was meant to make the variable differ from function name. If it's confusing I can change the variable name

2022-03-07 07:36 UTC, Agata-Gizinska commented on class_register.py
> +        with open(self.file, 'r+', newline='', encoding='utf-8') as file:
again commented up

2022-03-07 07:37 UTC, Agata-Gizinska commented on class_register.py
> +                file.truncate(0)
same

2022-03-07 07:37 UTC, Agata-Gizinska commented on class_register.py
> +                pass
ok

2022-03-07 07:39 UTC, Agata-Gizinska commented on class_register.py
> +
removed then

2022-03-07 08:03 UTC, Agata-Gizinska commented on class_register.py
> +        return self.courses
removed

2022-03-07 08:36 UTC, Agata-Gizinska commented on class_register.py
> +        register.add_student_to_course(student, student.courses[0])
Ok, removed wrapper in both Course and Classroom

2022-03-08 08:04 UTC, Agata-Gizinska commented on class_register.py
> +        def is_classroom_in_register(classroom):
moved to ClassroomRegister

2022-03-08 08:04 UTC, Agata-Gizinska commented on class_register.py
> +                            if not "''" else []
ok

2022-03-08 08:04 UTC, Agata-Gizinska commented on class_register.py
> +                            split(', ') if not "''" else []
ok

2022-03-08 08:05 UTC, Agata-Gizinska commented on class_register.py
> +        def is_course_in_register(course):
moved to CourseRegister

2022-03-08 08:05 UTC, Agata-Gizinska commented on class_register.py
> +                            if not "''" else []
ok

2022-03-08 08:12 UTC, Agata-Gizinska commented on class_register.py
> +        args_.append(course_reg)
ok

2022-03-08 08:13 UTC, Agata-Gizinska commented on class_register.py
> +                            if not "''" else []
ok

2022-03-08 08:13 UTC, Agata-Gizinska commented on class_register.py
> +                            split(',') if not "''" else []
ok

2022-03-08 08:15 UTC, Agata-Gizinska commented on class_register.py
> +    parser.add_argument('--new_student', '-newst', nargs=5,
Could you please elaborate?

2022-04-03 10:02 UTC, czarnadzuma11 commented on class_register.py
> +        new_student_ = Student(*args)
ok

2022-04-03 10:46 UTC, czarnadzuma11 commented on class_register.py
> +                file.truncate(0)
ok

2022-04-03 10:46 UTC, czarnadzuma11 commented on class_register.py
> +    parser.add_argument('--new_student', '-newst', nargs=5,
Describing what and in what order has to be entered explains how to use it TO THE USER but does not explain int TO THE PROGRAM.
This is why in code below we need to guess that
args.new_student[0] means student_name

You might have noticed that each command here expects a different set of arguments, this is almost as if each command should have its own parser. And we can do that with subparsers!


```
import argparse
parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest='command')

subparser = subparsers.add_parser('new-student')
subparser.add_argument('name')
subparser.add_argument('surname')

subparser = subparsers.add_parser('delete-student')
subparser.add_argument('id')

subparser = subparsers.add_parser('list')

args = parser.parse_args()
print(args)

if args.command == 'list':
    list_students()
elif args.command == 'new-student':
    add_student(args.name, args.surname)
```

an alternative (lame but quick) solution woiuld be to manually put new_student values into for example a dictionary dict['name'] = args.new_student[0] etc but it would not verify arguments at parsing and would require you to handle input errors yourself

2022-04-03 10:46 UTC, czarnadzuma11 commented on class_register.py
> +        first_course = args_[4]
Do not need to fix if you move to subparsers

2022-04-05 12:56 UTC, Agata-Gizinska commented on class_register.py
> +    parser.add_argument('--new_student', '-newst', nargs=5,
ok

2022-04-20 19:33 UTC, czarnadzuma11 approved these changes

2022-04-21 06:17 UTC, merged