Improved version of the Class Register program
Agata-Gizinska/Class_register pull request #3
Opened 2022-04-02 21:49 UTC by Agata-Gizinska

This is the improved Class Register after implementing initial feedback from [the previous pull request](https://github.com/Agata-Gizinska/Class_register/pull/2). 

Moreover, new features has been implemented:
- add new student
- add new course
- give grade
- add student to existing course
- graduate student
- drop out student

2022-04-03 11:03 UTC, czarnadzuma11 requested changes

2022-04-03 11:03 UTC, czarnadzuma11 commented on class_register.py
> +
Remove this, parser help already includes this information,

2022-04-03 11:03 UTC, czarnadzuma11 commented on class_register.py
> +    parser.add_argument('--print_classes', action='store_true',
Explanation is already included in help=, remove comments

2022-04-03 11:03 UTC, czarnadzuma11 commented on class_register.py
> +
Make those long elif cases into functions

2022-04-03 11:03 UTC, czarnadzuma11 commented on class_register.py
> +    is_classroom_in_register(classroom) \n
Triple " will preserve the formatting, you do not need to add \n manually

2022-04-03 11:03 UTC, czarnadzuma11 commented on class_register.py
> +    def is_classroom_in_register(self, classroom):
if function name begins with is_ I'd expect it to return true/false. You can rename it  to get_classroom and it will behave as the name would suggest

2022-04-03 11:03 UTC, czarnadzuma11 commented on class_register.py
> +        rows = self.read_rows_in_register()
Why would we not do self.read_rows_in_register() on register __init__ and at the same time do all of those strip and replaces that we need to do below?

2022-04-05 12:55 UTC, Agata-Gizinska commented on class_register.py
> +
ok

2022-04-05 12:56 UTC, Agata-Gizinska commented on class_register.py
> +    parser.add_argument('--print_classes', action='store_true',
ok

2022-04-05 12:56 UTC, Agata-Gizinska commented on class_register.py
> +
ok

2022-04-06 07:04 UTC, Agata-Gizinska commented on class_register.py
> +    is_classroom_in_register(classroom) \n
ok

2022-04-06 07:18 UTC, Agata-Gizinska commented on class_register.py
> +    def is_classroom_in_register(self, classroom):
ok

2022-04-12 06:16 UTC, Agata-Gizinska commented on class_register.py
> +        rows = self.read_rows_in_register()
implemented

2022-04-20 19:35 UTC, czarnadzuma11 approved these changes

2022-04-21 06:15 UTC, merged